[package]
name = "eosio_cli"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "eosrs"
path = "src/main.rs"
doc = false

[dependencies]
# clap = "2.32.0"
# futures = "0.1.20"
eosio = { version = "0.3", path = "../eosio" }
# eosio_rpc = { path = "../eosio_rpc", features = ["use-hyper"] }
# hyper = { version = "0.12" }
quote = "1.0"
structopt = "0.3"

[dependencies.syn]
version = "1.0"
default-features = false
features = [
    "full",
    "parsing",
    "visit",
    "clone-impls",
    "extra-traits",
]