language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
git:
  submodules: false
before_install:
  - docker pull sagansoftware/eosio.contracts:1.9.0
install:
  - rustup target add wasm32-unknown-unknown
  - rustup component add rustfmt
  - cargo install wasm-gc
  - cargo install mdbook
  - cargo install cargo-readme
services:
  - docker
script:
  - cargo unit-tests
  - cargo docker-tests
  - cargo build-docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target/doc
