condense_wildcard_suffixes = true
edition = "2018"
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
max_width = 80
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
