[package]
name = "eosio_numstr"
version = "0.3.1"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"
description = "Basic helper functions to work with EOSIO names and symbols"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["eos", "eosio", "blockchain", "crypto", "dapp"]
categories = [
    "cryptography::cryptocurrencies",
    "algorithms",
    "encoding",
    "parsing",
    "value-formatting"
]
repository = "https://github.com/sagan-software/eosio-rust"
homepage = "https://sagan-software.github.io/eosio-rust/"
documentation = "https://sagan-software.github.io/eosio-rust/eosio-numstr/"
include = [
    "/Cargo.toml",
    "/README.md",
    "/src/**/*.rs",
    "/LICENSE-APACHE",
    "/LICENSE-MIT"
]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "sagan-software/eosio-rust", branch = "master" }

[dev-dependencies]
criterion = "0.3"
proptest = "0.9.5"

[[bench]]
name = "benches"
harness = false
path = "benches/benches.rs"