[package]
name = "bench"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# plotters = "0.2.1"
regex = "1"
lazy_static = "1.3"
rand_regex = "0.14"
rand = "0.7"
rand_xorshift = "0.2"
# eosio = { path = "../../crates/eosio" }
# log = "0.4"
# pretty_env_logger = "0.3"
# structopt = "0.3"
# path-slash = "0.1"
util = { path = "../util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
