[package]
name = "scripts"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"


[dependencies]
plotters = "0.2.1"
regex = "1"
lazy_static = "1.3"
rand = "0.6"
eosio = { path = "../../crates/eosio" }
log = "0.4"
pretty_env_logger = "0.3"
structopt = "0.3"
path-slash = "0.1"
util = { path = "../util" }
