[package]
name = "eosio"
version = "0.3.1"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Core types and traits related to EOSIO blockchains"
repository = "https://github.com/sagan-software/eosio-rust"
keywords = ["eos", "eosio", "blockchain", "crypto", "dapp"]
categories = [
    "api-bindings",
    "cryptography::cryptocurrencies",
    "data-structures",
    "parsing",
    "value-formatting"
]
homepage = "https://sagan-software.github.io/eosio-rust/"
documentation = "https://sagan-software.github.io/eosio-rust/eosio-core/"
readme = "README.md"
include = [
    "Cargo.toml",
    "src/**/*.rs",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT"
]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "sagan-software/eosio-rust", branch = "master" }

[dependencies]
eosio_numstr = { version = "0.3.1", path = "../eosio_numstr" }
eosio_macros = { version = "0.3.1", path = "../eosio_macros" }

[dev-dependencies]
criterion = "0.3"
proptest = "0.9.5"

[[bench]]
name = "bytes"
harness = false
path = "benches/bytes.rs"